export const EVENT_HANDLERS = {
  onClick: `onClick`,
  onChange: 'onChange',
  onSubmit: 'onSubmit',
  onFocus: 'onFocus',
  onBlur: 'onBlur',
  onMouseEnter: 'onMouseEnter',
  onMouseLeave: 'onMouseLeave',
  onKeyDown: 'onKeyDown',
  onKeyUp: 'onKeyUp',
  onMouseMove: 'onMouseMove',
  onDoubleClick: 'onDoubleClick',
  onInput: 'onInput',
  onLoad: 'onLoad',
  onResize: 'onResize',
  onScroll: 'onScroll',
  onTouchStart: 'onTouchStart',
  onTouchEnd: 'onTouchEnd',
  onDrag: 'onDrag',
  onDrop: 'onDrop',
  onContextMenu: 'onContextMenu',
  onAnimationStart: 'onAnimationStart',
  onAnimationEnd: 'onAnimationEnd',
  onAnimationIteration: 'onAnimationIteration',
  onPointerDown: 'onPointerDown',
  onPointerUp: 'onPointerUp',
  onPointerCancel: 'onPointerCancel',
};
